"""
WoSafe AI Engine — Report Generator
AI-powered generation of legal reports, evidence packages, incident timelines, and safety audits.
"""

from datetime import UTC, datetime
from typing import Any

from loguru import logger


class ReportGenerator:
    """Generates structured reports from incident, emergency, and journey data."""

    async def generate_incident_summary(self, incident: dict, evidence: list[dict] | None = None) -> dict:
        """Generate a comprehensive incident summary report."""
        return {
            "report_type": "incident_summary",
            "generated_at": datetime.now(UTC).isoformat(),
            "title": f"Incident Report — {incident.get('title', 'Untitled')}",
            "summary": self._build_incident_summary(incident),
            "sections": [
                {
                    "title": "1. Incident Overview",
                    "content": (
                        f"**Category:** {incident.get('category', 'N/A')}\n"
                        f"**Severity:** {incident.get('severity', 'N/A')}\n"
                        f"**Status:** {incident.get('status', 'N/A')}\n"
                        f"**Date/Time:** {incident.get('created_at', 'N/A')}\n"
                        f"**Location:** {incident.get('address', 'N/A')} "
                        f"({incident.get('latitude', 'N/A')}, {incident.get('longitude', 'N/A')})"
                    ),
                },
                {
                    "title": "2. Detailed Description",
                    "content": incident.get("description", "No description provided."),
                },
                {
                    "title": "3. Evidence Log",
                    "content": self._build_evidence_section(evidence or []),
                },
                {
                    "title": "4. Witness & Community Verification",
                    "content": (
                        f"**Community Votes:** {incident.get('votes_count', 0)}\n"
                        f"**Verifications:** {incident.get('verification_count', 0)}\n"
                        f"**Views:** {incident.get('views_count', 0)}"
                    ),
                },
                {
                    "title": "5. Recommended Actions",
                    "content": self._generate_recommendations_text(incident),
                },
            ],
            "metadata": {
                "report_id": f"RPT-{datetime.now(UTC).strftime('%Y%m%d%H%M%S')}",
                "generated_by": "WoSafe AI Report Generator v1.0",
                "is_ai_generated": True,
                "evidence_count": len(evidence or []),
            },
        }

    async def generate_legal_report(self, incident: dict, evidence: list[dict] | None = None, timeline: list[dict] | None = None) -> dict:
        """Generate a formal legal report suitable for law enforcement."""
        report_id = f"LEGAL-{datetime.now(UTC).strftime('%Y%m%d%H%M%S')}"

        return {
            "report_type": "legal_report",
            "generated_at": datetime.now(UTC).isoformat(),
            "title": f"Legal Incident Report — {report_id}",
            "summary": f"Formal legal documentation for incident: {incident.get('title', 'Untitled')}",
            "sections": [
                {
                    "title": "LEGAL INCIDENT REPORT",
                    "content": (
                        f"**Report Number:** {report_id}\n"
                        f"**Date of Report:** {datetime.now(UTC).strftime('%B %d, %Y')}\n"
                        f"**Reporting Platform:** WoSafe Women's Safety Platform\n"
                        f"**Classification:** {incident.get('category', 'N/A').upper()}\n\n"
                        "---\n\n"
                        "This report has been automatically generated by the WoSafe platform "
                        "and contains time-stamped, GPS-verified data collected during the incident."
                    ),
                },
                {
                    "title": "INCIDENT DETAILS",
                    "content": (
                        f"**Type of Incident:** {incident.get('category', 'N/A')}\n"
                        f"**Severity Level:** {incident.get('severity', 'N/A')}\n"
                        f"**Date & Time of Incident:** {incident.get('created_at', 'N/A')}\n"
                        f"**GPS Location:** ({incident.get('latitude', 'N/A')}, {incident.get('longitude', 'N/A')})\n"
                        f"**Address:** {incident.get('address', 'N/A')}\n\n"
                        f"**Description:**\n{incident.get('description', 'No description provided.')}"
                    ),
                },
                {
                    "title": "EVIDENCE INVENTORY",
                    "content": self._build_legal_evidence_section(evidence or []),
                },
                {
                    "title": "EVENT TIMELINE",
                    "content": self._build_timeline_section(timeline or []),
                },
                {
                    "title": "DIGITAL VERIFICATION",
                    "content": (
                        "All data in this report has been:\n"
                        "- ✅ GPS-verified with location accuracy metadata\n"
                        "- ✅ Time-stamped with UTC timestamps\n"
                        "- ✅ Stored with tamper-proof integrity checks\n"
                        "- ✅ Captured through the WoSafe verified application\n\n"
                        f"**Community Verifications:** {incident.get('verification_count', 0)} independent verifications"
                    ),
                },
                {
                    "title": "DISCLAIMER",
                    "content": (
                        "This report has been generated automatically by the WoSafe AI system. "
                        "While all timestamps, GPS coordinates, and evidence are captured "
                        "with verified integrity, the narrative descriptions are user-submitted. "
                        "This document is intended to support, not replace, official police reports."
                    ),
                },
            ],
            "metadata": {
                "report_id": report_id,
                "generated_by": "WoSafe AI Legal Report Generator v1.0",
                "is_ai_generated": True,
                "is_legally_formatted": True,
                "evidence_count": len(evidence or []),
                "timeline_events": len(timeline or []),
            },
        }

    async def generate_emergency_timeline(self, session: dict, events: list[dict] | None = None, evidence: list[dict] | None = None) -> dict:
        """Generate an emergency session timeline report."""
        return {
            "report_type": "emergency_timeline",
            "generated_at": datetime.now(UTC).isoformat(),
            "title": f"Emergency Session Timeline — {session.get('id', 'N/A')}",
            "summary": f"Complete timeline of emergency session triggered at {session.get('created_at', 'N/A')}",
            "sections": [
                {
                    "title": "Session Overview",
                    "content": (
                        f"**Session ID:** {session.get('id', 'N/A')}\n"
                        f"**Trigger Type:** {session.get('trigger_type', 'N/A')}\n"
                        f"**Status:** {session.get('status', 'N/A')}\n"
                        f"**Escalation Level:** {session.get('escalation_level', 0)}\n"
                        f"**Police Notified:** {'Yes' if session.get('police_notified') else 'No'}\n"
                        f"**Medical Notified:** {'Yes' if session.get('medical_notified') else 'No'}\n"
                        f"**Started:** {session.get('created_at', 'N/A')}\n"
                        f"**Resolved:** {session.get('resolved_at', 'Not resolved')}"
                    ),
                },
                {
                    "title": "Location Trail",
                    "content": self._build_location_trail(session.get("location_trail", [])),
                },
                {
                    "title": "Notified Contacts",
                    "content": self._build_contacts_section(session.get("notified_contacts", [])),
                },
                {
                    "title": "Evidence Collected",
                    "content": self._build_evidence_section(evidence or []),
                },
            ],
            "metadata": {
                "report_id": f"EMR-{datetime.now(UTC).strftime('%Y%m%d%H%M%S')}",
                "generated_by": "WoSafe AI Timeline Generator v1.0",
                "is_ai_generated": True,
            },
        }

    async def generate_evidence_package(self, incident_id: str, evidence: list[dict], incident: dict | None = None) -> dict:
        """Generate a complete evidence package for an incident."""
        return {
            "report_type": "evidence_package",
            "generated_at": datetime.now(UTC).isoformat(),
            "title": f"Evidence Package — Incident {incident_id}",
            "summary": f"Complete evidence package containing {len(evidence)} items",
            "sections": [
                {
                    "title": "Evidence Manifest",
                    "content": f"**Total Evidence Items:** {len(evidence)}\n**Incident ID:** {incident_id}",
                },
                {
                    "title": "Evidence Items",
                    "content": self._build_legal_evidence_section(evidence),
                },
                {
                    "title": "Chain of Custody",
                    "content": (
                        "All evidence items were:\n"
                        "- Uploaded through the verified WoSafe application\n"
                        "- Stored in encrypted cloud storage (AES-256)\n"
                        "- Time-stamped at point of capture\n"
                        "- Associated with verified user accounts\n"
                        "- Chain of custody maintained through audit logs"
                    ),
                },
            ],
            "evidence_items": evidence,
            "metadata": {
                "report_id": f"EVD-{datetime.now(UTC).strftime('%Y%m%d%H%M%S')}",
                "generated_by": "WoSafe Evidence Package Generator v1.0",
                "evidence_count": len(evidence),
            },
        }

    # ── Helper Methods ──────────────────────

    def _build_incident_summary(self, incident: dict) -> str:
        category = incident.get("category", "unknown")
        severity = incident.get("severity", "unknown")
        return (
            f"A {severity}-severity {category} incident was reported "
            f"at {incident.get('address', 'an unspecified location')}. "
            f"Current status: {incident.get('status', 'unknown')}."
        )

    def _build_evidence_section(self, evidence: list[dict]) -> str:
        if not evidence:
            return "No evidence attached to this report."
        lines = []
        for i, e in enumerate(evidence, 1):
            lines.append(
                f"**{i}.** [{e.get('evidence_type', 'file')}] "
                f"{e.get('file_name', 'unnamed')} — "
                f"Uploaded: {e.get('created_at', 'N/A')}"
            )
        return "\n".join(lines)

    def _build_legal_evidence_section(self, evidence: list[dict]) -> str:
        if not evidence:
            return "No evidence items in this package."
        lines = ["| # | Type | Filename | Size | Timestamp |", "|---|------|----------|------|-----------|"]
        for i, e in enumerate(evidence, 1):
            size = e.get("file_size_bytes", 0)
            size_str = f"{size / 1024:.1f} KB" if size < 1024 * 1024 else f"{size / (1024*1024):.1f} MB"
            lines.append(
                f"| {i} | {e.get('evidence_type', 'N/A')} | "
                f"{e.get('file_name', 'unnamed')} | {size_str} | "
                f"{e.get('created_at', 'N/A')} |"
            )
        return "\n".join(lines)

    def _build_timeline_section(self, events: list[dict]) -> str:
        if not events:
            return "No timeline events recorded."
        lines = []
        for event in events:
            lines.append(
                f"- **{event.get('timestamp', 'N/A')}** — "
                f"{event.get('event_type', 'unknown')}: "
                f"({event.get('latitude', 'N/A')}, {event.get('longitude', 'N/A')})"
            )
        return "\n".join(lines)

    def _build_location_trail(self, trail: list[dict]) -> str:
        if not trail:
            return "No location trail data available."
        lines = []
        for i, point in enumerate(trail):
            lines.append(
                f"**{i + 1}.** ({point.get('lat', 'N/A')}, {point.get('lng', 'N/A')}) "
                f"at {point.get('timestamp', 'N/A')}"
            )
        return "\n".join(lines)

    def _build_contacts_section(self, contacts: list[dict]) -> str:
        if not contacts:
            return "No contacts were notified."
        lines = []
        for c in contacts:
            channels = ", ".join(c.get("channels", []))
            lines.append(
                f"- **{c.get('name', 'Unknown')}** ({c.get('phone', 'N/A')}) — "
                f"Channels: {channels} — Notified: {c.get('notified_at', 'N/A')}"
            )
        return "\n".join(lines)

    def _generate_recommendations_text(self, incident: dict) -> str:
        severity = incident.get("severity", "low")
        recs = ["- Document all evidence and preserve digital records"]
        if severity in ("critical", "high"):
            recs.extend([
                "- File an official police report (FIR) immediately",
                "- Contact a legal aid helpline for guidance",
                "- Seek medical attention if physically harmed",
                "- Preserve all communication records as evidence",
                "- Consider obtaining a restraining order if applicable",
            ])
        elif severity == "medium":
            recs.extend([
                "- Report to local authorities if the situation persists",
                "- Inform trusted friends and family members",
                "- Use WoSafe's Guardian Mode for continuous monitoring",
            ])
        else:
            recs.extend([
                "- Stay vigilant and report any escalation",
                "- Share your location with a trusted contact",
            ])
        return "\n".join(recs)


# Singleton
report_generator = ReportGenerator()
